### PR TITLE
Customizable menu window

### PR DESCRIPTION
**Pull request by jesseleite**
# Default Window

image

# Customized Window 💅 💅 💅

```lua
require('harpoon').setup {
  menu = {
    width = 50,
    height = 8,
    borderchars = {'!', '@', '$', '%', '^', '&', '*', '|'},
  }
}
```

```vim
highlight HarpoonWindow ctermbg=yellow ctermfg=red
highlight HarpoonBorder ctermbg=yellow ctermfg=red
```

custom

### CODE REVIEW

**Comment by jesseleite** [comment]
Btw, I think this could be a bit cleaner. I dug into both [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) and [popup.nvim](https://github.com/nvim-lua/popup.nvim) by Teej, and it seems they both both have pros and cons:

- Plenary can center the window for you, but doesn't let you customize border, etc.
- Popup lets you customize border, but you have to center the window yourself.
    - Teej [has this as a TODO though](https://github.com/nvim-lua/popup.nvim/blob/master/lua/popup/init.lua#L135), so I'll probably PR this into popup soon.

**Comment by jesseleite** [comment]
BTW, I dug into both plenary.nvim and popup.nvim by Teej, and it seems they both both have pros and cons:

- Plenary can center the window for you, but doesn't let you customize border, etc.
- Popup lets you customize border, but you have to center the window yourself.

Just PR'd a few potential improvements to popup.nvim, see:

- https://github.com/nvim-lua/popup.nvim/pull/9
- https://github.com/nvim-lua/popup.nvim/pull/10

If those get merged, we can simplify our code to this...

```lua
local win_id, win = popup.create(bufnr, {
    title = 'Harpoon',
    highlight = 'HarpoonWindow',
    borderhighlight = 'HarpoonBorder',
    minwidth = config.width or 60,
    minheight = config.height or 10,
    pos = 'center',
    borderchars = config.borderchars or { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
})
```

**Comment by jesseleite** [comment]
Rad thanks @ThePrimeagen 🤘 

PS. I'll PR the above simplification if/when my pop.nvim PRs get merged there.

**Comment by ThePrimeagen** [comment]
yeah, this is awesome

**Pull request merged**
