### PR TITLE
Save on change

### PR DESCRIPTION
**Pull request by ThePrimeagen**

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
@polarmutex 
@asbjornhaland
@brandoncc 

I keep Losing my file because vim closes before save can complete

**Comment by asbjornhaland** [comment]
Maybe we should save after every interaction. - rm and set_current_at as well.

**Comment by ThePrimeagen** [comment]
@asbjornhaland I love this idea!

Perhaps we should emit an event that way people can hook into it and even create their own actions afterwords

**Comment by asbjornhaland** [comment]
I agree, this sounds good.

**Comment by asbjornhaland** [comment]
BTW this is a duplicate of #43 , right?

**Comment by ThePrimeagen** [comment]
I'll get it all sorted first thing in morning

**Comment by ThePrimeagen** [comment]
there we go.  I think that is everything.  I will be testing it for the day, if all works out, I'll be merging it!

**Comment by asbjornhaland** [comment]
Nice, good work! Should we emit change for `store_offset()` and `toggle_file()` as well?

**Comment by ThePrimeagen** [comment]
@asbjornhaland toggle file does emit.  (it emits from add_file and rm_file)

store_offset... I never really thought about that... that is a good point.

**Comment by asbjornhaland** [comment]
Aah, yes, of course. LGTM, I guess you did not encounter any issues during the work day?

I think this means #43 can be closed.

**Comment by ThePrimeagen** [comment]
yes. it fixed several weirdsnesses I have experienced

**Pull request merged**
