### PR TITLE
fix: make enter_on_sendcmd work

### PR DESCRIPTION
**Pull request by clbrunet**
Closes the issue #120.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
@clbrunet left a quick remark .. sorry for the duration here

**Comment by clbrunet** [comment]
@ThePrimeagen Can't it be merged ?

**Comment by jeanlucthumm** [comment]
Can this be merged?

**Comment by MarkoSagadin** [comment]
It would be really nice if this could be merged :)

**Comment by MarkoSagadin** [comment]
The same change needs to be made in `sendCommand` function inside of  `tmux.lua` in order for the tmux commands to work.

**Comment by JSchrtke** [comment]
I tried this on windows, works here too. Looking forward to the merge ;)

**Comment by lucasclerissepro** [comment]
Tested on my side as well with native nvim termimal. Can we merge it @ThePrimeagen ?

**Comment by clbrunet** [comment]
@babygau it works without this pr depending on your shell configuration. If the shell configuration does not automatically execute a command (with a endline) pasted into the terminal, then the enter_on_sendcmd option does not work. Using a '\r' allows the enter_on_sendcmd option to work in both cases of shell configuration.

**Review by disrupted — APPROVED** [review]
tested locally, can confirm this is fixing the linked issue

**Pull request closed without merging**
