### PR TITLE
feat: cmd_ui Support sending tmux cmd

### PR DESCRIPTION
**Pull request by liuxian1990**
cmd_ui Support sending tmux cmd

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
I am very weary about merging anything into this.

1.  Its terrible code.  I hate what its become.
2.  If this breaks... I am not going to fix it.

Do you fully accept the responsibility?

**Comment by liuxian1990** [comment]
You are right that this code maintenance is really bad, but if you want CMD-UI to support tmux, can you let the user decide?

Please forgive me for improper grammar translation with translation software

example：
image

**Comment by Nhjkl** [comment]
image

For example, I maintain many projects with different versions of node， Simple management through harpoon，
It needs to be executed with the tmux background.

**Comment by Nhjkl** [comment]
@bangedorrunt 
I'm sorry I didn't write the instructions

It needs to declare the global variable implementing select_menu_item_callback

image

**Pull request merged**
