### PR TITLE
telescope extension

### LINKED ISSUE #56: Telescope
https://github.com/brandoncc/telescope-harpoon.nvim

this should be moved into this plugin to be more easily seen and known to be used. should be easy as copying the telescope folder into the lua folder here

### PR DESCRIPTION
**Pull request by polarmutex**
closes #56

plan on trying to support all the current harpoon ui inside the telescope plugin

### CODE REVIEW

**Comment by polarmutex** [comment]
do not  have a good solution to move marks to change the order,  any ideas would be appreciated

**Comment by brandoncc** [comment]
Wow, this has so much more functionality than my extension. Nicely done!

**Comment by mystilleef** [comment]
Works well. Way better than native UI. Kudos!

**Comment by mystilleef** [comment]
@polarmutex can you set the `Preview` to show the exact position of the mark? Currently, the `Preview` only shows the top of the document.

**Comment by polarmutex** [comment]
I am not sold on the current implementation of moving marks around, let me know if you have any better ideas

**Comment by ThePrimeagen** [comment]
I don't have any ideas, but I am pretty stoked about this.

**Comment by sQVe** [comment]
How do I actually use and register this to `telescope`. I'm a bit confused 🤔

**Comment by polarmutex** [comment]
Probably should update the readme, I always forget that, I will work on it

But basically add extension to telescope and call "Telescope harpoon marks"

**Comment by sQVe** [comment]
One thing I noted very quickly is that the entries seem to be truncated at a very short width. I would think that it should truncate at all.

image

**Comment by sQVe** [comment]
Also, is there a way to override the defaults keymap here? I would like the invert `<Ctrl-n>` and `<Ctrl-p>`.

**Comment by sQVe** [comment]
The entries seem to be truncated which I would assume it shouldn't be, since it breaks the ability to fuzzy search.

image

**Comment by mystilleef** [comment]
@polarmutex the `Preview` is still not showing the location of the harpoon mark for me. It still only shows the beginning of the file. Am I missing something?

**Comment by polarmutex** [comment]
i will take a look later today

**Comment by sQVe** [comment]
It would be nice if we could make the confirm delete optional too, or that it supports deleting multiple entries. It's kinda a hassle to run <kbd>Ctrl+d</kbd> + <kbd>y</kbd> for multiple entries.

**Comment by mystilleef** [comment]
Please test PR #130. It should fix the problem with the previewer not showing the exact location of marks.

**Pull request merged**
