### PR TITLE
Add feature to disable/enable wrapping on next/prev when cycling through harpoon lists.

### PR DESCRIPTION
**Pull request by mwishoff**
Implements the ask on #341. Allows for people to configure the usage of harpoon_wrap in harpoon:setup(). By default harpoon_wrap is True which keeps the wrapping behavior that already existed.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
Let's not call this harpoon_wrap, but instead ui_nav_wrap, and default value true

**Comment by mwishoff** [comment]
Updated the PR. should I update the rest of the formatting that's failing the check to get the format checker to pass?

**Comment by ThePrimeagen** [comment]
I'm not enforcing it at a local level yet, this is still exploratory branch. Things are going very good though

**Comment by ThePrimeagen** [comment]
I think we should be able to test this. Would you mind creating a failing test? Even if it's just eq(true, false) with a name for me to remember to create it

**Comment by jjiangweilan** [comment]
This feature has been moved. look at https://github.com/ThePrimeagen/harpoon/pull/461#issuecomment-1879332220

**Pull request merged**
