### PR TITLE
fix: Improve issue templates

### PR DESCRIPTION
**Pull request by theKnightsOfRohan**
Addresses issue #440 

# Bug Report:
Screenshot 2023-12-27 at 10 10 55 PM

# Feature Request:
Screenshot 2023-12-27 at 10 05 17 PM

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
i approve but i don't know why the format is failing.  I just pulled down latest...

**Comment by ThePrimeagen** [comment]
please investigate the styling issue and i'll merge this

**Comment by theKnightsOfRohan** [comment]
@ThePrimeagen I formatted the project, try it now

**Comment by ThePrimeagen** [comment]
I just realized this is against Master.

Please redo the PR against harpoon2

**Comment by theKnightsOfRohan** [comment]
> I just realized this is against Master.
> 
> Please redo the PR against harpoon2

Oh, ok. The old issue templates were in master, and there were none in harpoon2, which was why I thought to put them against master. Sorry about that. I'll fix it right up.

**Comment by theKnightsOfRohan** [comment]
I reopened this PR because the new issue templates are not showing up. I did some digging, and it appears that issue templates [must be on the default branch of the repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Pull request closed without merging**
