### PR TITLE
fix: Sometimes the statuscolumn disappears. Issue #559

### PR DESCRIPTION
**Pull request by abeldekat**
See issue [559](https://github.com/ThePrimeagen/harpoon/issues/559)

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
any details on this?  i am confused what the error is and what you are looking for

**Comment by abeldekat** [comment]
All details plus a reproducible `init` are in the related issue.
In the first video, at 0:15, you can observe that the `statuscolumn` is not present anymore: All line-numbers disappeared.

This happens quite regularly when using Harpoon2. It took some effort to find an exact scenario that is reproducible.

**Comment by dwtong** [comment]
EDIT: i was on neovim v0.9.5 and having this issue, updating to v0.10.0-dev fixed it.

@ThePrimeagen i am also having the same issue (i.e. i cannot see my line numbers aka status column) but it happens to me every time i close and reopen neovim and then jump to a harpoon mark. 

opening the same file without harpoon does not have this issue.

this PR solves it for me (see attached clip, where i make the same change as this PR, and it fixes it)

https://github.com/ThePrimeagen/harpoon/assets/7065184/c90ca8f8-4fb7-4efa-9344-9cc6306e35da

**Comment by abeldekat** [comment]
Hello @dwtong, 

Thanks for the confirmation!

> but it happens to me every time i close and reopen neovim and then jump to a harpoon mark.

If I am not mistaken, you essentially use the same steps I describe in issue #559 :


1. Open init.lua: repro init.lua
2. Place the cursor on line 52, requiring Harpoon
3. Harpoon add
4. Close Neovim
5. Open Neovim without arguments: repro
6. Harpoon select 1 (using the keymapping)

In the video, I also see `treesitter-context`, as expected.
Do you use a starter plugin?

**Comment by dwtong** [comment]
@abeldekat happy to help. yea, my steps were basically the same, also commenting out the line that you removed in this PR to demonstrate the fix. 

my config is based on [kickstart](https://github.com/nvim-lua/kickstart.nvim) but is basically hand rolled at this point. 

which version of neovim are you on? i was previously on v0.9.5, but then updated to v0.10.0-dev and it fixed this issue for me.

**Comment by abeldekat** [comment]
I use both 0.9.5 and nightly via "bob", and the issue is still present.

**Comment by abeldekat** [comment]
File `lua/harpoon/config.lua`:

On line 116: `if not vim.api.nvim_buf_is_loaded(bufnr) then`
This PR removes line 117: `vim.fn.bufload(bufnr)`

Closing as I am not using `harpoon` anymore.

**Pull request closed without merging**
