### PR TITLE
Fix1

### PR DESCRIPTION
**Pull request by ThePrimeagen**
@sug44 here you go

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
a couple of breaking tests... looking

**Comment by ThePrimeagen** [comment]
@sug44 removing exact path has caused bugs

**Comment by sug44** [comment]
the tests were breaking on the parent commit as well, so i didnt try to fix any of them

**Comment by ThePrimeagen** [comment]
yeah, but the removal has caused somethings

there is also the usage of realpath that is causing breaking

**Comment by ThePrimeagen** [comment]
also... i realized... i cannot have this change

i am going to have to think of something different.

this change breaks one of the core concepts of harpoon.  i can have 2 repos, both with the same `key()` in settings (think workspaces) and it will return the same results.  i _must_ have relative paths

**Comment by sug44** [comment]
Yeah i see now that something changed, I'll investigate. About the https://github.com/ThePrimeagen/harpoon/pull/568#discussion_r1558095717 comment. Yeah it looks wrong because its not apperent what `a` and `b` is, but the purpose of this `index_of` is to find a item from the list that corresponds with the given path, so `a` is always absolute path and `b` is always `listItem.value`. I think I'll just add some comments so it doesnt look so scary

**Pull request closed without merging**
